### PR TITLE
add timeouts to abc for free code repitition

### PR DESCRIPTION
**Pull request by kmanc**
Per https://github.com/RsaCtfTool/RsaCtfTool/issues/339, this adds timeouts to attacks in the abstract base class, which cleans up code for many attacks and also prevents hanging if machines don't have the resources necessary to run attacks in a reasonable time

### CODE REVIEW

**Comment by kmanc** [comment]
@daedalus this one is the timeout one, with code cleanup on all the now-unnecessary timeout code in attacks

**Review by daedalus — CHANGES_REQUESTED** [review]
Its seems that this PR has some editions of the PR #344, so in order to be able to merge this PR we need to address first the issues with the later.

**Comment by kmanc** [comment]
Oh shoot, my bad. I thought I had those separate. Lemme see if I can fix that

**Comment by daedalus** [comment]
Please address first the things I pointed out in the later PR so we can move forward. I think this code will be mergeable but we need to look to it after solving the later PR.

**Comment by kmanc** [comment]
Undid the changes here. I think when I started the timeouts branch on my machine I didn't do it from master (whoops). This _might_ end up having a merge conflict with the other branch, but if it does, it'll be a simple fix on imports that I'll take care of

**Comment by daedalus** [comment]
Yup it has conflicts, please lift the conflicts and we can proceed to test and merge.

**Comment by kmanc** [comment]
Woahhh shit I think I messed that up. Jesus, I'm so sorry this has been a pain for you

**Comment by daedalus** [comment]
Hi, no problem, the thing that works for me is to create a new branch for every new PR. Maybe you need to do that and reply your work on top of that. 
Send a new PR if everthing checks it will be merged.

**Pull request closed without merging**
