### PR TITLE
Updated convert_idrsa_pub function

### PR DESCRIPTION
**Pull request by shraddha761**

### CODE REVIEW

**Comment by shraddha761** [comment]
@daedalus

**Comment by daedalus** [comment]
Since p and q are None in `pub_key, priv_key = generate_keys_from_p_q_e_n(None, None, e, n)` it will generate pub_key with an object and privkey = None, and since you are checking for the condition` if pub_key and priv_key:` it will always fail...
Maybe you want something like: `pub_key, _ = generate_keys_from_p_q_e_n(None, None, e, n)`, just ignore the private_key variable in your check...

**Comment by shraddha761** [comment]
> Since both `p and q = None` in `pub_key, priv_key = generate_keys_from_p_q_e_n(None, None, e, n)` it will generate `pub_key !=None` and `privkey = None`, and since you are checking for the condition` if pub_key and priv_key:` it will always fail... Maybe you want something like: `pub_key, _ = generate_keys_from_p_q_e_n(None, None, e, n)`, just ignore the private_key variable in your check...

OK.
Thank you i got it. 
Thanks :)

**Comment by shraddha761** [comment]
> Since both `p and q = None` in `pub_key, priv_key = generate_keys_from_p_q_e_n(None, None, e, n)` it will generate `pub_key !=None` and `privkey = None`, and since you are checking for the condition` if pub_key and priv_key:` it will always fail... Maybe you want something like: `pub_key, _ = generate_keys_from_p_q_e_n(None, None, e, n)`, just ignore the private_key variable in your check...

So, Should i update the code by removing private_key or close the PR.

**Comment by daedalus** [comment]
Please update to simething like this:
```
pub_key, _ = generate_keys_from_p_q_e_n(None, None, e, n) 
if pub_key:
   ...
```

**Comment by shraddha761** [comment]
> Please update to something like this:
> 
> ```
> pub_key, _ = generate_keys_from_p_q_e_n(None, None, e, n) 
> if pub_key:
>    ...
> ```

OK. :)

**Comment by shraddha761** [comment]
@daedalus review.

**Comment by daedalus** [comment]
Please replace the variable `priv_key`  with: `_`

**Comment by shraddha761** [comment]
> Please replace the variable `priv_key` with: `_`

DONE.

**Comment by daedalus** [comment]
also: `if n != None and e != None:` can be changed to`if n and e:`

**Comment by shraddha761** [comment]
> also: `if n != None and e != None:` can be changed to`if n and e:`

apologies, I m currently new to python

**Comment by daedalus** [comment]
Merged, thanks!!!

**Pull request merged**
